name: Build and Push

on:
  push:
    branches:
      - main
      - main-thesis
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/**'
      - '.tekton/**'
    tags:
      - v*

jobs:
  # Ensure that tests pass before publishing a new image.
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Build develop image
        run: make build.develop
      - name: Run lint
        run: ./scripts/develop.sh make fmt
      - name: Build runtime image
        run: make build
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo $VERSION
          
          DOCKER_IMAGE=${{ secrets.DOCKER_USER }}/modelmesh-controller

          # Use Docker `latest` tag convention     
          [ "$VERSION" == "main-thesis" ] && VERSION=latest
          echo $VERSION
          
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          
          docker tag ${TAGS}
          docker push ${TAGS}
